// Package record defines the immutable, append-only record that is the unit of
// storage, sync and encryption across the mesh, plus its canonical encoding and
// signature scheme.
//
// Records are never mutated in place. Edits and deletes are new records with a
// populated Supersedes list. This is the decision the rest of the system is
// built on: sync becomes set reconciliation, structural conflicts become
// impossible, and an offline write needs no reconciliation logic when it
// eventually lands (plan §2.1).
//
// Append-only eliminates structural conflict, not semantic conflict. Two agents
// can still assert contradictory things — both valid, both signed, neither
// superseding the other. That is handled by conflict policy, not by this
// package.
//
// # Contract stability
//
// The canonical encoding here is a frozen wire and storage contract (plan §11).
// Fields may be appended only behind a bumped FormatVersion, and CausalCtx and
// Evidence are present from the start precisely because they cannot be
// retrofitted once records are signed.
package record

import (
	"errors"
	"fmt"
	"sort"

	"github.com/coryforsythe/memmesh/internal/hlc"
	"github.com/coryforsythe/memmesh/internal/ulid"
)

// FormatVersion is the canonical encoding version, carried as the first byte of
// every encoded record. A reader that does not recognise it must refuse the
// record rather than guess.
const FormatVersion byte = 1

// SigSize is the length of an ed25519 signature.
const SigSize = 64

// PublicKeySize is the length of an ed25519 public key, which is how an AgentID
// is carried on the wire.
const PublicKeySize = 32

// Structural limits. They exist so a malicious or broken peer cannot make a
// receiving node allocate without bound, and so the canonical encoding has a
// predictable worst case.
const (
	// MaxBodyBytes caps a record body. Bodies are UTF-8 text or a blob hash;
	// anything larger belongs in the blob store behind an artifact_ref.
	MaxBodyBytes = 1 << 20
	// MaxTags caps the tag count on one record.
	MaxTags = 64
	// MaxTagBytes caps one tag.
	MaxTagBytes = 128
	// MaxSupersedes caps how many records one record may supersede.
	MaxSupersedes = 256
	// MaxRefs caps how many related records one record may point at.
	MaxRefs = 256
	// MaxCausalEntries caps the size of a carried version vector.
	MaxCausalEntries = 512
	// MaxModelIDBytes caps the author_model and embed_model strings.
	MaxModelIDBytes = 128
)

// Errors returned by Validate, Decode and Verify.
var (
	// ErrInvalid reports a record that fails structural validation.
	ErrInvalid = errors.New("record: invalid")
	// ErrNotCanonical reports an encoding whose byte order does not match what
	// the canonical encoder would produce. Refusing it is what makes the
	// signature non-malleable: there is exactly one signable encoding of a
	// record.
	ErrNotCanonical = errors.New("record: encoding is not canonical")
	// ErrUnsupportedVersion reports a record from a newer format version.
	ErrUnsupportedVersion = errors.New("record: unsupported format version")
	// ErrBadSignature reports a signature that does not verify against the
	// record's author agent key.
	ErrBadSignature = errors.New("record: signature does not verify")
	// ErrTruncated reports an encoding that ended early.
	ErrTruncated = errors.New("record: encoding truncated")
)

// Record is an immutable memory entry.
//
// The zero Record is not valid; build one with a Builder or by decoding.
type Record struct {
	// ID is a ULID generated by the authoring node. Sortable, and the
	// high-water key of a version vector.
	ID ulid.ULID `json:"id"`

	// Space is the space this record belongs to: the unit of subscription,
	// encryption and sync.
	Space SpaceID `json:"space"`

	// AuthorNode is the machine that produced the record. It keys version
	// vectors.
	AuthorNode NodeID `json:"author_node"`

	// AuthorAgent is the ed25519 public key of the authoring agent — per agent,
	// not per machine, so one agent can be attributed or revoked without
	// touching the others.
	AuthorAgent AgentID `json:"author_agent"`

	// AuthorModel records which model produced the content, for audit only.
	// Never filter on it: a Gemini-authored fact must be fully legible to
	// Claude (plan §7).
	AuthorModel string `json:"author_model"`

	// HLC totally orders records for tiebreaking. It is not evidence of
	// causality; CausalCtx is.
	HLC hlc.HLC `json:"hlc"`

	// Epoch is the key epoch the record was written under. Member removal
	// rotates the space key into a new epoch, and records carry which one they
	// belong to (plan §3.2).
	Epoch uint32 `json:"epoch"`

	// Kind classifies the record.
	Kind Kind `json:"kind"`

	// Body is UTF-8 text, or a content hash for an artifact_ref.
	Body []byte `json:"body"`

	// Tags are sorted and deduplicated by the canonical encoder.
	Tags []string `json:"tags,omitempty"`

	// Supersedes lists the records this one replaces. Required for tombstone
	// and retraction; permitted on any kind so an agent can post a corrected
	// fact directly.
	Supersedes []ulid.ULID `json:"supersedes,omitempty"`

	// Refs points at related records without replacing them. A conflict record
	// names both contradictory sides here; the link tool writes edges here.
	//
	// Refs is emphatically not Supersedes. Siblings in a conflict must both be
	// kept and both be returned, so the record that links them cannot use the
	// field that means replacement.
	Refs []ulid.ULID `json:"refs,omitempty"`

	// CausalCtx is what the author had seen at write time. It is what separates
	// "saw it and disagreed" from "never saw it and wrote blind".
	CausalCtx VersionVector `json:"causal_ctx,omitempty"`

	// Evidence ranks how the claim is backed. It outranks recency in conflict
	// resolution.
	Evidence Evidence `json:"evidence"`

	// EmbedModel pins the embedding model the author used. Vectors are never
	// synced, so on receive a node re-embeds locally; a mismatch here degrades
	// recall silently, which is why it is a health check (plan §4.3, §8.4).
	EmbedModel string `json:"embed_model"`

	// Sig is ed25519 over the canonical encoding, by AuthorAgent. It is not
	// part of the signed bytes.
	Sig [SigSize]byte `json:"sig"`
}

// Normalize puts the record's repeated fields into canonical order, sorting and
// deduplicating tags and supersedes. It is idempotent, and Canonical calls it,
// so callers rarely need it directly.
func (r *Record) Normalize() {
	if len(r.Tags) > 0 {
		sort.Strings(r.Tags)
		r.Tags = dedupeStrings(r.Tags)
	}
	if len(r.Supersedes) > 0 {
		sort.Slice(r.Supersedes, func(i, j int) bool {
			return r.Supersedes[i].Compare(r.Supersedes[j]) < 0
		})
		r.Supersedes = dedupeULIDs(r.Supersedes)
	}
	if len(r.Refs) > 0 {
		sort.Slice(r.Refs, func(i, j int) bool {
			return r.Refs[i].Compare(r.Refs[j]) < 0
		})
		r.Refs = dedupeULIDs(r.Refs)
	}
	if len(r.Tags) == 0 {
		r.Tags = nil
	}
	if len(r.Supersedes) == 0 {
		r.Supersedes = nil
	}
	if len(r.Refs) == 0 {
		r.Refs = nil
	}
	if len(r.CausalCtx) == 0 {
		r.CausalCtx = nil
	}
}

// Validate checks the record against the structural contract. It does not check
// the signature; use Verify for that.
func (r *Record) Validate() error {
	if r.ID.IsZero() {
		return fmt.Errorf("%w: id is zero", ErrInvalid)
	}
	if err := r.Space.Validate(); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalid, err)
	}
	if !r.AuthorNode.Valid() {
		return fmt.Errorf("%w: author_node %q is not a valid node id", ErrInvalid, string(r.AuthorNode))
	}
	if r.AuthorAgent.IsZero() {
		return fmt.Errorf("%w: author_agent is unset", ErrInvalid)
	}
	if len(r.AuthorModel) > MaxModelIDBytes {
		return fmt.Errorf("%w: author_model is %d bytes, max %d", ErrInvalid, len(r.AuthorModel), MaxModelIDBytes)
	}
	if len(r.EmbedModel) > MaxModelIDBytes {
		return fmt.Errorf("%w: embed_model is %d bytes, max %d", ErrInvalid, len(r.EmbedModel), MaxModelIDBytes)
	}
	if err := validateKind(r.Kind); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalid, err)
	}
	if err := validateEvidence(r.Evidence); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalid, err)
	}
	if len(r.Body) > MaxBodyBytes {
		return fmt.Errorf("%w: body is %d bytes, max %d", ErrInvalid, len(r.Body), MaxBodyBytes)
	}
	if len(r.Tags) > MaxTags {
		return fmt.Errorf("%w: %d tags, max %d", ErrInvalid, len(r.Tags), MaxTags)
	}
	for _, tag := range r.Tags {
		if tag == "" {
			return fmt.Errorf("%w: empty tag", ErrInvalid)
		}
		if len(tag) > MaxTagBytes {
			return fmt.Errorf("%w: tag %q is %d bytes, max %d", ErrInvalid, tag, len(tag), MaxTagBytes)
		}
	}
	if len(r.Supersedes) > MaxSupersedes {
		return fmt.Errorf("%w: %d supersedes, max %d", ErrInvalid, len(r.Supersedes), MaxSupersedes)
	}
	for _, id := range r.Supersedes {
		if id.IsZero() {
			return fmt.Errorf("%w: supersedes contains the zero id", ErrInvalid)
		}
		if id == r.ID {
			return fmt.Errorf("%w: record supersedes itself", ErrInvalid)
		}
	}
	if r.Kind.Supersedable() && len(r.Supersedes) == 0 {
		return fmt.Errorf("%w: kind %q requires a non-empty supersedes list", ErrInvalid, string(r.Kind))
	}
	if len(r.Refs) > MaxRefs {
		return fmt.Errorf("%w: %d refs, max %d", ErrInvalid, len(r.Refs), MaxRefs)
	}
	for _, id := range r.Refs {
		if id.IsZero() {
			return fmt.Errorf("%w: refs contains the zero id", ErrInvalid)
		}
		if id == r.ID {
			return fmt.Errorf("%w: record refers to itself", ErrInvalid)
		}
	}
	// A conflict record carries no claim of its own, so the records it links are
	// the only thing it says. One side is not a conflict.
	if r.Kind == KindConflict && len(r.Refs) < 2 {
		return fmt.Errorf("%w: kind %q requires at least two refs, got %d", ErrInvalid, string(r.Kind), len(r.Refs))
	}
	if len(r.CausalCtx) > MaxCausalEntries {
		return fmt.Errorf("%w: causal_ctx has %d entries, max %d", ErrInvalid, len(r.CausalCtx), MaxCausalEntries)
	}
	for node, id := range r.CausalCtx {
		if !node.Valid() {
			return fmt.Errorf("%w: causal_ctx node %q is not a valid node id", ErrInvalid, string(node))
		}
		if id.IsZero() {
			return fmt.Errorf("%w: causal_ctx entry for %q is the zero id", ErrInvalid, string(node))
		}
	}
	return nil
}

// IsSupersession reports whether this record exists to replace others.
func (r *Record) IsSupersession() bool { return len(r.Supersedes) > 0 }

// SawRecord reports whether the author had seen the given record when they
// wrote this one, according to the carried causal context.
//
// This is the question that separates disagreement from ignorance: a
// contradicting record whose author had seen the claim it contradicts is a
// considered disagreement, and one whose author had not is a blind write.
// Resolution should treat those differently.
func (r *Record) SawRecord(other *Record) bool {
	return r.CausalCtx.Covers(other.AuthorNode, other.ID)
}

// Clone returns a deep copy, so a caller can hand a record across an ownership
// boundary without the recipient being able to mutate the original's slices.
func (r *Record) Clone() *Record {
	out := *r
	if r.Body != nil {
		out.Body = append([]byte(nil), r.Body...)
	}
	if r.Tags != nil {
		out.Tags = append([]string(nil), r.Tags...)
	}
	if r.Supersedes != nil {
		out.Supersedes = append([]ulid.ULID(nil), r.Supersedes...)
	}
	if r.Refs != nil {
		out.Refs = append([]ulid.ULID(nil), r.Refs...)
	}
	out.CausalCtx = r.CausalCtx.Clone()
	return &out
}

func dedupeStrings(in []string) []string {
	out := in[:1]
	for _, s := range in[1:] {
		if s != out[len(out)-1] {
			out = append(out, s)
		}
	}
	return out
}

func dedupeULIDs(in []ulid.ULID) []ulid.ULID {
	out := in[:1]
	for _, id := range in[1:] {
		if id != out[len(out)-1] {
			out = append(out, id)
		}
	}
	return out
}
